#!/usr/bin/env python3
from __future__ import annotations

import json
import re
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
PORTFOLIO = ROOT / "portfolio"
INDEX_PATH = PORTFOLIO / "index.yaml"
GRAPH_MD = PORTFOLIO / "DEPENDENCY-GRAPH.md"
GRAPH_JSON = PORTFOLIO / "dependency-graph.json"


def load_yaml(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as handle:
        data = yaml.safe_load(handle)
    if not isinstance(data, dict):
        raise ValueError(f"{path}: expected a YAML mapping")
    return data


def node_id(project_id: str) -> str:
    return "p_" + re.sub(r"[^A-Za-z0-9_]", "_", project_id)


def mermaid_label(value: str) -> str:
    return value.replace('"', "'")


def main() -> None:
    index = load_yaml(INDEX_PATH)["portfolio"]

    project_paths = [PORTFOLIO / rel for rel in index.get("project_records", [])]
    contract_paths = [PORTFOLIO / rel for rel in index.get("contract_records", [])]

    projects: dict[str, dict] = {}
    for path in project_paths:
        record = load_yaml(path).get("project")
        if not isinstance(record, dict) or not record.get("id"):
            raise ValueError(f"{path}: missing project.id")
        project_id = str(record["id"])
        if project_id in projects:
            raise ValueError(f"duplicate project id: {project_id}")
        projects[project_id] = record

    contracts: list[dict] = []
    for path in contract_paths:
        record = load_yaml(path).get("contract")
        if not isinstance(record, dict) or not record.get("id"):
            raise ValueError(f"{path}: missing contract.id")
        source = str(record.get("source_project", ""))
        target = str(record.get("target_project", ""))
        if source not in projects:
            raise ValueError(f"{path}: unknown source_project {source!r}")
        if target not in projects:
            raise ValueError(f"{path}: unknown target_project {target!r}")
        contracts.append(record)

    contract_ids = {str(c["id"]) for c in contracts}
    for project_id, project in projects.items():
        for rel in project.get("contracts", []) or []:
            contract_name = Path(str(rel)).stem
            if contract_name not in contract_ids:
                raise ValueError(
                    f"{project_id}: contract reference {rel!r} is not registered in portfolio.index"
                )

    hard_pairs: set[tuple[str, str]] = set()
    for contract in contracts:
        if contract.get("hard_dependency") is True:
            direction = contract.get("dependency_direction") or {}
            dependent = str(direction.get("dependent") or contract["target_project"])
            dependency = str(direction.get("dependency") or contract["source_project"])
            hard_pairs.add((dependent, dependency))

    uncovered_dependencies: list[tuple[str, str]] = []
    for project_id, project in projects.items():
        for dependency in project.get("dependencies", []) or []:
            dep = str(dependency)
            if dep not in projects:
                raise ValueError(f"{project_id}: unknown dependency {dep!r}")
            if (project_id, dep) not in hard_pairs:
                uncovered_dependencies.append((project_id, dep))

    if uncovered_dependencies:
        formatted = ", ".join(f"{a} -> {b}" for a, b in uncovered_dependencies)
        raise ValueError(
            "hard project dependencies require an explicit hard_dependency contract: "
            + formatted
        )

    connected = sorted(
        {
            str(c["source_project"])
            for c in contracts
        }
        | {
            str(c["target_project"])
            for c in contracts
        }
    )
    hard_contracts = sorted(
        [c for c in contracts if c.get("hard_dependency") is True],
        key=lambda c: str(c["id"]),
    )
    soft_contracts = sorted(
        [c for c in contracts if c.get("hard_dependency") is not True],
        key=lambda c: str(c["id"]),
    )

    structural_review = str(index.get("last_structural_review") or "UNKNOWN")

    lines = [
        "# Dependency Graph",
        "",
        "> Generated from `portfolio/projects/*.yaml` and verified `portfolio/contracts/*.yaml`.",
        "> Do not edit this file manually. Run `python portfolio/scripts/generate_dependency_graph.py`.",
        "",
        f"**Project records:** {len(projects)}  ",
        f"**Verified contracts:** {len(contracts)}  ",
        f"**Hard dependency contracts:** {len(hard_contracts)}  ",
        f"**Soft relationship contracts:** {len(soft_contracts)}  ",
        f"**Connected projects:** {len(connected)}  ",
        f"**Projects with no verified cross-project contract:** {len(projects) - len(connected)}  ",
        f"**Structural review:** {structural_review}",
        "",
        "## Verified graph",
        "",
        "```mermaid",
        "flowchart LR",
    ]

    for project_id in connected:
        project = projects[project_id]
        status = str(project.get("status", "UNKNOWN"))
        label = mermaid_label(f"{project_id}\\n[{status}]")
        lines.append(f'    {node_id(project_id)}["{label}"]')

    for contract in sorted(contracts, key=lambda c: str(c["id"])):
        source = str(contract["source_project"])
        target = str(contract["target_project"])
        relations = " / ".join(str(x) for x in contract.get("relations", []))
        if contract.get("hard_dependency") is True:
            lines.append(
                f'    {node_id(source)} -->|"{relations} · HARD"| {node_id(target)}'
            )
        else:
            lines.append(
                f'    {node_id(source)} -.->|"{relations} · soft"| {node_id(target)}'
            )

    lines += [
        "```",
        "",
        "A solid arrow means the relationship contains an explicit hard dependency. "
        "A dashed arrow is a verified relationship but not a runtime requirement.",
        "",
        "## Hard dependencies",
        "",
        "| Dependent | Dependency | Contract |",
        "|---|---|---|",
    ]

    if hard_contracts:
        for contract in hard_contracts:
            direction = contract.get("dependency_direction") or {}
            dependent = str(direction.get("dependent") or contract["target_project"])
            dependency = str(direction.get("dependency") or contract["source_project"])
            lines.append(f"| `{dependent}` | `{dependency}` | `{contract['id']}` |")
    else:
        lines.append("| — | — | — |")

    lines += [
        "",
        "## Verified non-hard relationships",
        "",
        "| Source | Target | Relations | Contract |",
        "|---|---|---|---|",
    ]

    if soft_contracts:
        for contract in soft_contracts:
            relations = ", ".join(str(x) for x in contract.get("relations", []))
            lines.append(
                f"| `{contract['source_project']}` | `{contract['target_project']}` | "
                f"{relations} | `{contract['id']}` |"
            )
    else:
        lines.append("| — | — | — | — |")

    lines += [
        "",
        "## Invariant",
        "",
        "> A project-level `dependencies` entry is invalid unless a registered contract "
        "declares the same relationship with `hard_dependency: true`.",
        "",
        "This keeps the graph evidence-backed and prevents accidental coupling from becoming architecture.",
        "",
    ]

    graph = {
        "schema_version": 1,
        "structural_review": structural_review,
        "project_count": len(projects),
        "verified_contract_count": len(contracts),
        "connected_project_count": len(connected),
        "connected_nodes": [
            {
                "id": project_id,
                "repository": projects[project_id].get("repository"),
                "status": projects[project_id].get("status"),
                "role": projects[project_id].get("role"),
            }
            for project_id in connected
        ],
        "edges": [
            {
                "id": str(c["id"]),
                "source": str(c["source_project"]),
                "target": str(c["target_project"]),
                "relations": list(c.get("relations", [])),
                "hard_dependency": bool(c.get("hard_dependency") is True),
            }
            for c in sorted(contracts, key=lambda c: str(c["id"]))
        ],
    }

    GRAPH_MD.write_text("\n".join(lines), encoding="utf-8")
    GRAPH_JSON.write_text(
        json.dumps(graph, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
